READMEを作成した
pau12377/Florence pull request #13
Opened 2022-08-25 02:28 UTC by pau12377

fix #2

## 背景

## やったこと

## やってないこと

## レビューしてほしい観点

## 補足資料

2022-08-31 09:00 UTC, TakeshiYoshi requested changes
何点かコメントしました！
修正お願いいたします:bow:

2022-08-31 09:00 UTC, TakeshiYoshi commented on README.md
> +現状はWebサイトが無く、Webからもアパートの情報がわかるようにし、多くのユーザーに認知されたいと考えたためです。
> 多くのユーザーに認知されたいと考えたためです。

多くのユーザー とありますが、ユーザーというよりは入居希望者ではないでしょうか？
ユーザーというとサービスの利用者のようなイメージを持ってしまいます。

2022-08-31 09:00 UTC, TakeshiYoshi commented on README.md
> +### ・なぜそれをやるのか？
```suggestion

```

この小見出しは不要なように感じます

2022-08-31 09:00 UTC, TakeshiYoshi commented on README.md
> +### ・このIssueで何を成し遂げたいのか？
これは README であり Issue ではないですよね？
なのでこの小見出しは少し違和感を感じます。

2022-08-31 09:00 UTC, TakeshiYoshi commented on README.md
> +サイト全体の概要を明白にし、わかりやすく伝えるため制作いたしました。
この文言も README を書く理由のように見え、README に記載するには違和感を感じます。

2022-08-31 09:00 UTC, TakeshiYoshi commented on README.md
> +Webサイトを完成させ、リリースをすることです。
これは Issue の description に記載するような内容ですね。
README に書くのは不適切に感じます。

2022-08-31 09:00 UTC, TakeshiYoshi commented on README.md
> +https://daiwajyutaku.com/
参考は Issue にまとめておいて RAEDME には記載しなくて良いと思います。

2022-08-31 09:00 UTC, TakeshiYoshi commented on README.md
> +```
サイトマップが書いてあるの親切で良いと思います👍

2022-08-31 09:59 UTC, pau12377 commented on README.md
> +サイト全体の概要を明白にし、わかりやすく伝えるため制作いたしました。
「このIssue（README）で何を成し遂げたいのか？」の部分は、READMEを書く理由とは違うのでしょうか…？
READMEに記載するべき内容では無ければ、項目を削除してもよいでしょうか？

2022-08-31 10:01 UTC, pau12377 commented on README.md
> +Webサイトを完成させ、リリースをすることです。
Issue の description とはどのIssueになりますか？

2022-08-31 10:03 UTC, pau12377 commented
READMEに書くべき内容の質問になりますが、
「背景」
「ゴールインパクト」
「期限」
「サイトマップ」
「カンプ」
でよろしいでしょうか？

2022-08-31 10:07 UTC, TakeshiYoshi commented on README.md
> +Webサイトを完成させ、リリースをすることです。
どこかのIssueに書いてくださいと言ってるのではなく、この文言はIssueに書くような内容でREADMEに書くような内容では無いですよねというレビューコメントです。

READMEはこのリポジトリ(で作るサイト)はどのようなものかを説明するものになります。
サイトの説明に「Webサイトを完成させ、リリースをすることです。」と書いてあったら不自然ですよね？

2022-08-31 10:10 UTC, TakeshiYoshi commented on README.md
> +サイト全体の概要を明白にし、わかりやすく伝えるため制作いたしました。
READMEにREADMEを書く理由には奈

2022-08-31 10:18 UTC, TakeshiYoshi commented
@pau12377 
決まりは無いですが
- 概要
どういうサイトなのか？
デプロイしていればURLやトップページのスクショも付けると🙆
- 背景
どういった経緯・目的でサイトを作ったのか？
- ターゲット
どういった人をターゲットにしているのか？
- カンプ
- サイトマップ

は最低限欲しいですね。

2022-09-04 15:28 UTC, TakeshiYoshi requested changes
修正案を書いたので修正を検討してみてください。

2022-09-04 15:28 UTC, TakeshiYoshi commented on README.md
> +そのアパートを紹介するWebサイトです。
```suggestion
本リポジトリはFlorenceについて情報をまとめたサイトのWordPressテンプレートになります。
```

こそあどは使わないようにした方が読者が読みやすくなります。

2022-09-04 15:28 UTC, TakeshiYoshi commented on README.md
> +Webからもアパートの情報がわかるようにし、より多くの入居希望者を獲得したいと考えたため、サイトを作成しようと思いました。
```suggestion
現状、FlorenceのWebサイトは存在せず、インターネットから情報を調べることができません。
近年入居者が減っており、入居者を増やしたいという課題を抱えておりました。
入居者のターゲットが学生ということもあり、インターネットで情報を得られることで入居者増が見込めると思い、本サイトを作成することになりました。
```

2022-09-04 15:28 UTC, TakeshiYoshi commented on README.md
> +10代〜20代
```suggestion
- 群馬大学医学部に入学する予定の女子学生
- 10代〜20代
```

箇条書きにしましょうか

2022-09-04 15:28 UTC, TakeshiYoshi commented on README.md
> +## カンプ
```suggestion
## カンプ
カンプの画像は作成後挿入します
```

2022-09-05 09:12 UTC, TakeshiYoshi approved these changes
LGTM👍

2022-09-05 09:12 UTC, TakeshiYoshi commented on README.md
> +
[nits]
行間の改行はいらないと思います。
次READMEを編集するときに直しておくと良いかもです。

2022-09-08 05:52 UTC, merged