PC用のフッターを作成した
pau12377/Florence pull request #29
Opened 2022-09-09 16:03 UTC by pau12377

fix #24 

## 背景
Florenceのサイトを作成するために、最初にフッターを作成した。
サイト内のコンテンツの量がそれほど大きくないため、フッターはコピーライトのみにした。

## やったこと
- ディレクトリの作成や環境設定をした
- src/scss内のstyle.scssに各scss（_vw_l.scssなど）を読み込ませて、style.cssに出力した
- PC用のみフッターを作成

## やってないこと
- スマホ用のフッターは作成していない
- <main>タグ内の「テキスト…」はダミーなので後で別の内容に書き換える

## レビューしてほしい観点
- クラス名の書き方はBEMを参考にしたが問題ないか
- ディレクトリの構成は問題ないか

2022-09-12 03:07 UTC, pau12377 commented
追加データについての補足です。
_reset.scssはリセットcssです。
デフォルトで付属しているcssを打ち消すため書きました。

2022-09-12 03:51 UTC, pau12377 commented
### Priprosについて

PreprosはSassを簡単にコンパイルすることがきるGUIツールです。

参考
[https://prepros.io/](url)

2022-09-13 09:34 UTC, TakeshiYoshi commented
補足説明ありがとうございます👍
レビューする際の助けになるので助かります！
使用したツールはREADMEに使用したツール欄を設けて書いておくと実績になりそうですね👍

2022-09-13 09:53 UTC, TakeshiYoshi requested changes
コメントしました🙋
ご確認よろしくおねがいします。

2022-09-13 09:53 UTC, TakeshiYoshi commented on src/scss/_vw_l.scss
> +      box-shadow: -2px -7px 20px -5px rgb(rgb(189, 189, 189), 0.2);
```suggestion
      box-shadow: -2px -7px 20px -5px rgba(189, 189, 189, 0.2);
```

rgbaというパラメータがあるのでこちらを使用しましょう

2022-09-13 09:53 UTC, TakeshiYoshi commented on src/scss/_vw_l.scss
> +      box-shadow: -2px -7px 20px -5px rgb(rgb(189, 189, 189), 0.2);
```suggestion
      box-shadow: -2px -7px 20px -5px rgba(#bdbdbd, 0.2);
```

SCSSで書くなら上記のように16進数カラーコードで書くこともできます。
カラーはカラー定義するファイルに変数として保存しておくと再利用性が増してメンテナンスしやすいコードになりと思います。

2022-09-13 09:53 UTC, TakeshiYoshi commented on index.html
> +      <span class="Florence__copyright__icon">&copy;</span>Florence
BEMの命名規則は
B: Block
E: Element
M: Modifier
です。
流派はありますが `B__E--M` がオーソドックスだと思います。

今回の場合は `Florence__copyright--icon` ではないでしょうか？
後述しますが `Florence__copyright--icon` も変なので `Florence__icon` にすべきだと思います。

2022-09-13 09:53 UTC, TakeshiYoshi commented on src/scss/_vw_l.scss
> +      &__icon{
今回の場合、iconは Modifier にはあたらないと思います。
Modifier とは、例えばタブがあった時に、選択されたタブの色のみ変えたい場合に
`side-menu__tab`, `side-menu__tab--current` のように命名し区別します。
状態を表現する箇所といえばよいでしょうか。

ですので、iconは `florence__icon` でよいと思います。

2022-09-13 09:53 UTC, TakeshiYoshi commented on src/scss/_vw_l.scss
> +.Florence {
このクラスは必要でしょうか？
bodyをBlockとするのは大きすぎる気がします。

フッターを `footer` というBlockにして、
copyright を `footer__copyright` というElement, icon を `footer__icon` にしてみてはどうでしょうか？

2022-09-13 12:43 UTC, pau12377 commented
## TODO
- [ ] フォルダ分けをする
- [ ] カラーを変数で管理する
- [ ] SCSSの構造を修正する

2022-09-14 01:39 UTC, TakeshiYoshi requested changes
数点コメントしましたので確認お願いします。

2022-09-14 01:39 UTC, TakeshiYoshi commented on src/scss/_vw_l.scss
>  }
文脈から `_vw_l.scss` はパソコン用スタイルのファイルだと思っていましたがあっていますでしょうか？
その場合、パソコンのみ `font-family: "Noto Sans JP", sans-serif;` という指定をするのですか？

2022-09-14 01:39 UTC, TakeshiYoshi commented on src/scss/variables/_font.scss
> +$footer_font: 12px;
フォントサイズは xs, sm, normal, lg, xl, 2xl, ... というように定義すると再利用性が増します。
`$footer_font` ですとフッターにしか使えなくなってしまいますので、例えば
`$sm: 12px;` 等で定義してみることをおすすめします。
そして、グローバルな変数(どこでも使うような変数) は `v_` という prefix を付けましょう。
https://mimemo.io/m/qOX6eWonbowPDQ8

最終的には以下のような状態を期待してます。(あくまで例なので調整してくださいね)

```scss
// font-size
$V_FONT_SIZE_XS: 12px;
$V_FONT_SIZE_SM: 14px;
$V_FONT_SIZE_NORMAL: 16px;
$V_FONT_SIZE_LG: 18px;
$V_FONT_SIZE_XL: 22px;

// font-family
$V_FONT_FAMILY_MAIN: "Noto Sans JP": 

// font-weight
$V_FONT_WEIGHT_THIN: 100;
$V_FONT_WEIGHT_LIGHT: 300;
$V_FONT_WEIGHT_NORMAL: 500;
$V_FONT_WEIGHT_BOLD: 700;
$V_FONT_WEIGHT_BLACK: 900;
```

2022-09-14 01:39 UTC, TakeshiYoshi commented on src/scss/variables/_color.scss
> +$footer_color: #fff;
カラーの変数名も抽象化して更に名前をつけたい時は抽象化した変数を使用しましょう。
以下は例です。

```scss
// GRAY にも後々、少し濃い目の GRAY など別の GRAY を定義したいケースも出てきます。
// 以下のように、GRAY0 とすることで GRAY1, GRAY2 と別の GRAY も定義出来るようにしておきます。
$V_COLOR_WHITE0: #ffffff;
$V_COLOR_GRAY0: #bdbdbd;

// 以下は例で書いていますが、基本的には以下のようなことはせず上記の変数を使うべきです

// Florence
$shadow: $V_COLOR_GRAY0;

// footer
$footer_color: $V_COLOR_WHITE;
```

2022-09-14 01:40 UTC, TakeshiYoshi commented
description に完成したフッターのスクリーンショットを貼るようにしましょう

2022-09-14 07:14 UTC, pau12377 commented
## TODO
- [ ] フォントの変数を抽象化する
- [ ] カラーの変数を抽象化する
- [ ] スクリーンサイズを変数で書く
- [ ] description に完成したフッターのスクリーンショットを貼る

2022-09-14 16:40 UTC, TakeshiYoshi approved these changes
LGTM👍
良くなりましたね！

2022-09-14 16:45 UTC, merged