[Florence TOP]PC用のヘッダーを作成した
pau12377/Florence pull request #36
Opened 2022-09-12 15:43 UTC by pau12377

fix #22 
## 背景
FlorenceのサイトのPC用ヘッダーを作成した。
ここで作成したヘッダーはFlorenceのTOPページのみで使用し、
FlorenceA、FlorenceBのヘッダーはそれぞれ別で作成する予定。

## やったこと
- 左側にsvgで出力したロゴを配置
- 右側にメニューを配置、ホバー時に下線を表示させた
- contactのみ色を付け、ホバー時に色が濃くなるよう実装した

## やってないこと
- スマホ用のヘッダーは作成していない
- リンク先はダミー

## レビューしてほしい観点
- クラス名を一部付けていない箇所があるが、全て付けた方が良いかどうか
- scssの構成が正しいかどうか

2022-09-14 17:12 UTC, pau12377 commented on index.html
> +  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
コメント

2022-09-14 17:22 UTC, pau12377 commented
## TODO
- [ ] クラス名の命名規則を変更する
- [ ] 変数を変更する
- [ ] コミットしたら呼ぶ（プッシュできないため）

2022-09-20 11:13 UTC, TakeshiYoshi requested changes
コメントしました。確認よろしくおねがいします！

2022-09-20 11:13 UTC, TakeshiYoshi commented on src/scss/modules/_header.scss
> +  width: 100%;
これは不要ではないですか？

2022-09-20 11:13 UTC, TakeshiYoshi commented on src/scss/modules/_header.scss
> +  justify-content: flex-end;
`header__card` で `display: flex;` をしているなら不要ではないですか？
また、
```css
  align-items: center;
  justify-content: flex-end;
```
はどういった意図で入れたのでしょうか？

2022-09-20 11:13 UTC, TakeshiYoshi commented on src/scss/modules/_header.scss
> +  height: 80px;
親要素いっぱいに表示したいのなら `height: 100%;` が適切ではないでしょうか？
親要素の高さが変わった時にこちらも変更が必要になりますよね？

2022-09-20 11:13 UTC, TakeshiYoshi commented on src/scss/modules/_header.scss
> +  font-family: "kefa", sans-serif;
フォントは変数化しましょう

2022-09-21 06:37 UTC, pau12377 commented
## TODO
- [ ] 完成後のスクショを取る
- [ ] フォント、 transitionを変数に入れる
- [ ] ヘッダーのz-indexを大きい数値にする
- [ ] ヘッダーはposition: absoluteを使わずにflexのみで実装する

2022-09-23 09:24 UTC, TakeshiYoshi requested changes
レビューしました！
ご確認よろしくおねがいします！

2022-09-23 09:24 UTC, TakeshiYoshi commented on src/scss/variables/_animation.scss
> +$V_TRANSITION3000: all 0.3s ease;
3000だと3000ms => 3s になってしまいますよ
$V_TRANSITION_300MS とかどうですか？

2022-09-23 09:24 UTC, TakeshiYoshi commented on src/scss/modules/_header.scss
> +  align-items: center;
この2つはどういった意図で記述したのでしょうか？

2022-09-23 09:24 UTC, TakeshiYoshi commented on src/scss/modules/_header.scss
> +  margin: 0 20px;
`margin-left: 20px;` でも良い気がしますので検討してみてください。

2022-09-23 09:26 UTC, TakeshiYoshi commented on src/scss/modules/_header.scss
> +  align-items: center;
もし `align-items: center;` をしたいなら `display: flex;` を指定している親要素(`header`クラス)で定義しましょう。

2022-09-26 04:38 UTC, pau12377 commented on src/scss/modules/_header.scss
> +  align-items: center;
ヘッダーに対し、高さを基準にして中央揃えさせるため記述しました。

2022-09-26 05:00 UTC, pau12377 commented on src/scss/modules/_header.scss
> +  align-items: center;
親要素(`header`クラス)に`align-items: center;`を定義するとcontactの高さが取れなくなってしまいました。
そのため.header__logoに記述しています。
![スクリーンショット 2022-09-26 13 58 02](https://user-images.githubusercontent.com/110820784/192197167-f4d32f80-5647-4caf-b781-f9109d9ff8ae.png)

2022-09-26 05:17 UTC, pau12377 commented
## TODO
- [ ] transitionの変数名を修正する
- [ ] ヘッダーのmarginの数値の修正

2022-09-27 08:29 UTC, TakeshiYoshi approved these changes
LGTM👍

2022-09-27 08:30 UTC, merged