[Florence]スマホ用のヘッダーを作成した
pau12377/Florence pull request #44
Opened 2022-09-20 10:55 UTC by pau12377

fix #23 

## 背景
Florenceのスマホ用ヘッダーを作成した。
ここで作成したヘッダーはFlorenceで使用する。
FlorenceAとFlorenceBのヘッダーはメニュー項目が変わるため、今回作成したFlorenceに項目を追加して作成していく。

## やったこと
- ロゴをスマホ用に差し替える
- PC用メニューを非表示にし、スマホ用メニューを表示させる
- スマホ用メニューが表示された場合、メニュー以外を暗くする

## やってないこと
- カーソルのホバー時ポインター表示させる（後で修正予定）

## レビューしてほしい観点
- メニュー以外を暗くする処理をするために”menu__background”というクラスを作成したが、headerタグの下に配置して良いか

2022-09-20 10:58 UTC, pau12377 commented on index.html
> +          />
ロゴはPC用とスマホ用別のものを表示させています。

2022-09-20 11:12 UTC, pau12377 commented on src/scss/modules/_header.scss
> +  .header__card {
.header__nav-button__lineがメニューボタンの線の部分になります。

2022-09-28 05:10 UTC, pau12377 commented
## TODO
- [ ] コードのリファクタリングをする（不要なコードは消す）
- [ ] 変数に置き換える

2022-10-02 16:27 UTC, TakeshiYoshi requested changes
いくつかコメントしました。
レビュー遅くなり申し訳ないです:pray:

2022-10-02 16:27 UTC, TakeshiYoshi commented on src/scss/modules/_header.scss
> +    margin-top: 0px;
こちら記述いらないと思います。

2022-10-02 16:27 UTC, TakeshiYoshi commented on src/scss/modules/_header.scss
>      transition: all 0.3s ease;
全部に記述しているので `.header__nav-button__line` に書いてもよいと思います。

2022-10-02 16:27 UTC, TakeshiYoshi commented on src/scss/modules/_header.scss
> +    text-align: left;
こちら不要だと思います

2022-10-02 16:27 UTC, TakeshiYoshi commented on index.html
>        <nav class="header__nav">
クラス名を `navigation` にした方がよいと思います。

2022-10-02 16:27 UTC, TakeshiYoshi commented on index.html
> +        <button class="navigation">
こちらのクラス名を `navigation__button` にすると良いと思います。

2022-10-02 16:27 UTC, TakeshiYoshi commented on index.html
> +          <span class="navigation__line"></span>
line だと navigation ブロックの中に line という Element があるように受け取れてしまうので
`navigation__button-line` というのはどうでしょうか？

2022-10-03 06:14 UTC, TakeshiYoshi approved these changes
LGTM👍
BEMらしい命名になって良いと思いました。
headerブロックとnavigationブロックに分離することでheaderのSCSSがファットでなくなったのもGoodです！

2022-10-03 06:36 UTC, merged