[Florence TOPページ]PC用のNewsを作る
pau12377/Florence pull request #49
Opened 2022-10-02 15:02 UTC by pau12377

fix #31 
## 背景
FlorenceのサイトのPC用Newsを作成した。
ここで作成したNewsはFlorenceのTOPページとFlorenceA、FlorenceBで使用する。

## やったこと
- Newsタイトルの作成
- Newsの内容の作成

## イメージ
![スクリーンショット 2022-10-03 0 01 45](https://user-images.githubusercontent.com/110820784/193461010-f8d7e0cd-785d-45be-bb8f-c87d7c4eacf9.png)

2022-10-02 15:05 UTC, pau12377 commented on src/scss/_global.scss
> +.inner {
innerは幅1000pxに設定しています。
また、innerは他のページでも使用するためglobal.scssに記載しました。

2022-10-11 14:28 UTC, TakeshiYoshi requested changes
いくつかコメントしました。
ご確認よろしくおねがいします！

2022-10-11 14:28 UTC, TakeshiYoshi commented on index.html
>          <div class="inner">
`news__wrap` は news ブロックのブロックに当たると思うので `news` クラスにしたほうがよいと思います。
また `inner` クラスは `news__wrap` と同じ div に定義でも良いかなと思いましたがいかがでしょうか？

2022-10-11 14:28 UTC, TakeshiYoshi commented on index.html
> +          <h1 class="news">
こちらは変えるなら `news__title` とかでしょうか？

2022-10-11 14:28 UTC, TakeshiYoshi commented on index.html
> +            </div>
この `news__title` と `news__title--head` を分けた意味は何でしょうか？
`news__title--head` に一括で定義しちゃっても良いかなと思いました。

2022-10-11 14:28 UTC, TakeshiYoshi commented on index.html
> +            <div class="news__title--small">新着情報</div>
ここは `h1` タグから外して `h2` タグにすべきだと思いました。

2022-10-11 14:28 UTC, TakeshiYoshi commented on index.html
> +            <div class="news__text__wrap">
`news__card` な要素はこちらでは？

2022-10-11 14:28 UTC, TakeshiYoshi commented on index.html
> +          <div class="news__card">
こちらの `div` は不要だと思いました。
このコミットの 60行目 の div要素に集約してはいかがでしょうか？

2022-10-11 14:28 UTC, TakeshiYoshi commented on index.html
> +                <span class="news__day">10月31日</span>
day だと 日 なので date とか time はいかがでしょうか？

2022-10-11 14:53 UTC, pau12377 commented on index.html
> +              <p class="news__text">
ネスト深すぎ。上の要素に定義できないか検討

2022-10-11 16:23 UTC, pau12377 commented
## TODO
- [ ] news__wrapをnewsに変更する
- [ ] news__cardをnews__boxに変更し、innerと同じdivタグに入れる
- [ ] h1のnewsをnews__titleに変更する、h2タグにする
- [ ] news__title--smallをnews__subtitleに変更、h3タグにする
- [ ] news__text__wrapをnews__cardに変更する
- [ ] news__textを削除
- [ ] news__yearとnews__dayを一行にする、クラス名をnews__dateにする

2022-10-18 06:16 UTC, TakeshiYoshi approved these changes
LGTM👍
1つコメントしましたが別Issueでやりましょう！

2022-10-18 06:16 UTC, TakeshiYoshi commented on index.html
> +            <span class="news__data">2022年10月31日</span>
data になっているので date にする fixチケット作りましょう！

2022-10-18 08:07 UTC, merged