[Florence TOP]PC用のメインビジュアルを作成した
pau12377/Florence pull request #56
Opened 2022-10-11 06:50 UTC by pau12377

fix #30
## 背景
FlorenceのサイトのPC用メインビジュアルを作成した。
メインビジュアルはswiperというプラグインを使用し、スライダーを作成した。
スライダーの設定はstyle.jsで行った。

## やったこと
- スライダーを作成した
- キャッチコピーを作成した
- ページネーションの位置と色を調整した
- 空室情報の位置とサイズを変更した

## 補足
### swiperの使用したオプション
- `effect: "fade"` フェードで切り替わる
- `delay: 3000`　次のスライドに切り替わる時間を指定（ミリ秒）
- `autoplay:disableOnInteraction: false`　ユーザーが操作した場合自動再生を止める（falseは止めない）
- `loop: true,`　ループを無限にする
- `speed: 1000`　スライド切り替えのアニメーションのスピードを指定（ミリ秒）
- `pagination:el: ".swiper-pagination"`　ページネーションを設定する
- `pagination:type: "bullets"`　ページネーションの形を表示する
- `clickable: true,`　クリックでのスライド切り替えを有効にする

## イメージ
![スクリーンショット 2022-10-11 15 49 26](https://user-images.githubusercontent.com/110820784/195016295-f7e28dda-5c00-4e5a-9353-ed44416f9761.png)

2022-10-11 14:13 UTC, TakeshiYoshi requested changes
いくつかコメントしました。
ご確認よろしくおねがいします！

2022-10-11 14:13 UTC, TakeshiYoshi commented on src/scss/modules/_mainvisial.scss
> +}
`.swiper-pagination-bullet-active` が付与されている要素には `.swiper-pagination-bullet` が必ず付与されているのでこの定義は不要だと思います。

2022-10-11 14:13 UTC, TakeshiYoshi commented on src/scss/modules/_mainvisial.scss
> +}
この定義はどういう意図があったのでしょうか？
`.swiper-pagination-bullet` に対して `margin: 2px;` したいのでしたらクラスに対してそのまま定義でも良いかなと思いました。

2022-10-11 14:13 UTC, TakeshiYoshi commented on src/scss/modules/_mainvisial.scss
> +  width: 1000px;
なるべく固有の値は使用しないようにしましょう。
親要素で `width: 1000px;` を定義しているのなら `width: 100%;` にすべきです。

2022-10-11 14:13 UTC, TakeshiYoshi commented on src/scss/modules/_mainvisial.scss
> +  z-index: 999;
ヘッダーとは事情が変わってくると思うのである程度のバッファを持たせつつ小さめの数値にしましょう。
`z-index: 5;` 程度でしょうか。

2022-10-11 14:13 UTC, TakeshiYoshi commented on src/scss/variables/_font.scss
> +$V_FONT_SIZE_TITLE_NORMAL: 32px;
TITLEなどの固有の名称は使わずに抽象化した名称にしましょう。
たとえば `2XL`, `3XL`, `4XL` などどうでしょうか？

2022-10-11 14:13 UTC, TakeshiYoshi commented on src/scss/modules/_mainvisial.scss
> +  padding: 30px;
`padding: 30px;` と敢えて padding を定義したのは意図があったのでしょうか？
width, height に 180px を定義すれば同義だと思いました。

2022-10-11 14:13 UTC, TakeshiYoshi commented on src/scss/modules/_mainvisial.scss
> +  z-index: 999;
こちらもキャッチフレーズ同様に数値を見直してみてください。

2022-10-11 14:37 UTC, pau12377 commented on src/scss/variables/_color.scss
> +$V_COLOR_BRAUN: #312626;
スペルミス

2022-10-12 08:55 UTC, pau12377 commented
## TODO
- [ ] .swiperのwidthを100%にする
- [ ] .swiper-slideのスライダーを削除
- [ ] .swiper-pagination-bullet-activeの内容を.swiper-pagination-bulletに移す
- [ ] .swiper-wrapperの定義を見直す
- [ ] .swiper-vacancy__wrapの定義を見直す
- [ ] z-indexの数値を見直す

### fontの変更
- [ ]  font-familyの変数名を抽象化する
- [ ]  $V_FONT_SIZE_TITLEの名称を変更し、2XL等で表記する
- [ ] colorのスペルミスを直す

2022-10-13 10:38 UTC, pau12377 commented on src/scss/modules/_swiper.scss
> +  width: unset !important;
`.swiper-horizontal > .swiper-pagination-bullets,
.swiper-pagination-bullets.swiper-pagination-horizontal,
.swiper-pagination-custom,	
.swiper-pagination-fraction { }` でCSS定義されているため `!important` を指定しないと適応されない。

2022-10-18 06:10 UTC, TakeshiYoshi approved these changes
LGTM👍

2022-10-18 06:35 UTC, merged